openapi: 3.0.3
info:
  title: Product Pricing API
  description: Consulta de precios aplicables
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /v1/capitole/product/pricing/applicable:
    get:
      tags:
        - product-pricing-handler
      summary: Obtiene el precio aplicable de un producto
      operationId: getApplicablePrice
      parameters:
        - name: date
          in: query
          description: Fecha en formato ISO 8601
          required: true
          schema:
            type: string
            format: date-time
        - name: product_id
          in: query
          description: ID del producto
          required: true
          schema:
            type: integer
        - name: brand_id
          in: query
          description: ID de la marca
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Precio encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
        '400':
          description: Parámetros inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerResponse'
        '404':
          description: No se encontró precio aplicable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerResponse'
components:
  schemas:
    PriceResponse:
      type: object
      description: Respuesta con el precio aplicable
      properties:
        productId:
          type: integer
          format: int64
          description: ID del producto
          example: 35455
        brandId:
          type: integer
          format: int64
          description: ID de la marca
          example: 1
        priceList:
          type: integer
          format: int64
          description: ID de la tarifa o price list
          example: 1
        startDate:
          type: string
          format: date-time
          description: Fecha de inicio de validez del precio
        endDate:
          type: string
          format: date-time
          description: Fecha de fin de validez del precio
        price:
          type: number
          description: Precio final
          example: 35.5
    ServerResponse:
      type: object
